### ISSUE TITLE
You need to have Advanced Custom Fields Pro installed to make the theme work properly!

### ISSUE THREAD

**Issue by CL1001** [MEDIADUDES/FoundationPress#10]
Fresh server instance, newly installed Wordpress. Build and installed the theme successfully (not using Local by Flywheel as the host as in previous attempts to install and use/build this theme, rather using LAMP).

I'm getting a warning that I need ACF Pro ... is this expected?

**How can this bug be reproduced?**

1. Install per instructions
2. Move folder to appropriate path on server
3. Activate theme

**What did you expect to happen?**
Not see an error in the admin panel

**What happened instead?**
Error: "You need to have Advanced Custom Fields Pro installed to make the theme work properly!"

**Please List the Following:**
* OS & version: Fedora Core 28  5.0.16-100.fc28.x86_64
* Node version: v11.13.0
* FoundationPress version: 3.4.3
* Foundation version : foundation-sites@6.6.3

**Include Test Case** (if applicable):  

I don't see how I can do this.

![ACF_PRO](https://user-images.githubusercontent.com/44201888/123640430-256d2e80-d7ef-11eb-9301-1cb75b46e23d.png)

**Comment by SimonMayerhofer** [comment]
Yes this is expected, as the theme is built upon ACF functionality like their Gutenberg Block functionality. But as this is a starter theme feel free to just remove that functionality (basically just the `inc/advanced-custom-fields.php` file) and customize it for your needs.

**Comment by CL1001** [comment]
Thank you SimonMayerhofer. Appreciated!
