### ISSUE TITLE
Cannot Add User In wp-admin - password Input Box is Broken

### ISSUE THREAD

**Issue by CL1001** [MEDIADUDES/FoundationPress#14]
**How can this bug be reproduced?**

1. Install FoundationPress per instructions
2. Zip theme folder & upload via wordpress, & activate theme
3. Attempt to add user

**What did you expect to happen?**
Add user should work

**What happened instead?**
The password input box is not displaying and therefore cannot be used. This happens on all of my deployed themes (I tested 5, and then stopped testing). Since I've never added a user after a installing a theme, this has never cropped up before. I affirm that changing themes to any other theme the functionality of adding a user works correctly on the 5 different installations 

**Please List the Following:**
* OS & version: Fedora Core 28 64
* Node version (node -v) [Node v4+ is required] : v10.19.0 & v11.13.0
* FoundationPress version (see line 3 in package.json): "version": "3.4.1", (actually this is in line 4)
* Foundation version (found in node_modules/foundation-sites/package.json) : foundation-sites@6.6.3

**Include Test Case** (if applicable):  
I don't see how I can do that.
![add_user](https://user-images.githubusercontent.com/44201888/137728182-6abfd350-e8f0-41d7-8c70-274e634b5ee0.png)
![add_user2](https://user-images.githubusercontent.com/44201888/137728184-fdc1291e-bf87-4cdf-8afc-39519df1dd0a.png)

Thank you.

**Comment by SimonMayerhofer** [comment]
Thank you for reporting! The issue was, that the password box used the `data-reveal` attribute like foundation for their reveals. I excluded the page now.

<img width="693" alt="Screenshot 2021-10-18 at 14 25 14" src="https://user-images.githubusercontent.com/4314302/137731465-bad5d9b2-a9cd-44e0-9e97-6b0156e86b82.png">

Release will be there in a moment.

**Comment by CL1001** [comment]
Thank you for your work and the reply. Will I be able to update existing projects, and if so, how?

**Comment by SimonMayerhofer** [comment]
Have a look at the commit: https://github.com/MEDIADUDES/FoundationPress/commit/656476760c1b269f18c5ca1a34b33a360d8f2baf
I just added a check around the admin enqueues. Depending on which theme version your other projects are, you should be able to just replace the function with the updated one. Alternatively just add the check manually:

```
global $pagenow;
// fix password field is removed
if ( 'user-new.php' !== $pagenow ) {
	// enqueues...
}
```

**Comment by CL1001** [comment]
Thank you so much!! Sincerely appreciated.

**Comment by CL1001** [comment]
Bingo!! I generated diff > patch, then patched file on a per-project basis. Perfect!!

Thank you SimonMayerhofer, very much.
