### ISSUE TITLE
Not an issue 

### ISSUE THREAD

**Issue by dantahoua** [MEDIADUDES/FoundationPress#5]
Hello!
Just here to say a big thanks. I was using Foundation Press for a long time, even contribute for some translation and bug correction in the past. Was sad to see the project is discontinued but here you are with an updated version.
I was about to update it but as you already made it!
Will keep an eye on this one and maybe add some update and helpers I made along the way.
V.

**Comment by SimonMayerhofer** [comment]
Hey Vincent, thanks for your kind words! I'm looking forward to your contributions. Feel free to add a issue beforehand so we can discuss prior. :)
