### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function acf_add_options_page

### ISSUE THREAD

**Issue by CL1001** [MEDIADUDES/FoundationPress#8]
**How can this bug be reproduced?**

1. Install FoundationPress (Mediadudes) per instructions https://github.com/MEDIADUDES/FoundationPress (quickstart) on Live By Local dev environment (been using it for a couple of years for wordpress site development)
2.  run either npm run build or npm run dev
3. Attempt live preview

**What did you expect to happen?**
Expected to see live preview

**What happened instead?**
Fatal Error

**Please List the Following:**
* OS & version: Fedora Core 28 64
* Node version (node -v) [Node v4+ is required] : v10.19.0 & v11.13.0
* FoundationPress version (see line 3 in package.json): 	"version": "3.4.1", (actually this is in line 4)
* Foundation version (found in `node_modules/foundation-sites/package.json`) : foundation-sites@6.6.3

**Include Test Case** (if applicable):  Don's see how I can do that.
Text output of error:

( ! ) Fatal error: Uncaught Error: Call to undefined function acf_add_options_page() in /../Local Sites/foundationpress-mediadudes/app/public/wp-content/themes/FoundationPress/inc/advanced-custom-fields.php on line 68
( ! ) Error: Call to undefined function acf_add_options_page() in /../Local Sites/foundationpress-mediadudes/app/public/wp-content/themes/FoundationPress/inc/advanced-custom-fields.php on line 68
Call Stack
#	Time	Memory	Function	Location
1	0.0001	407640	{main}( )	.../customize.php:0
2	0.0001	408912	require_once( '/../Local Sites/foundationpress-mediadudes/app/public/wp-admin/admin.php' )	.../customize.php:13
3	0.0001	409552	require_once( '/../Local Sites/foundationpress-mediadudes/app/public/wp-load.php' )	.../admin.php:34
4	0.0002	409992	require_once( '/../Local Sites/foundationpress-mediadudes/app/public/wp-config.php' )	.../wp-load.php:37
5	0.0003	420280	require_once( '/../Local Sites/foundationpress-mediadudes/app/public/wp-settings.php' )	.../wp-config.php:77
6	0.0364	3261592	do_action( )	.../wp-settings.php:560
7	0.0364	3261968	WP_Hook->do_action( )	.../plugin.php:484
8	0.0364	3261968	WP_Hook->apply_filters( )	.../class-wp-hook.php:316
9	0.0548	3540480	ACF->init( )	.../class-wp-hook.php:292
10	0.0634	4203912	do_action( )	.../acf.php:325
11	0.0634	4204288	WP_Hook->do_action( )	.../plugin.php:484
12	0.0634	4204288	WP_Hook->apply_filters( )	.../class-wp-hook.php:316
13	0.0634	4205416	foundationpress_add_option_pages( )	.../class-wp-hook.php:292
There has been a critical error on this website. Please check your site admin email inbox for instructions.
///////////////////////////////////////////////////////////////////

**Comment by SimonMayerhofer** [comment]
Thanks for the bug report. Just pushed a fix for it. Even though I don't really get how that can happen as this function is only called when ACF is loaded with the `acf/init` hook.

**Comment by CL1001** [comment]
I attempted with a fresh install to be met with similar fatal issue.

/////////////////////////////////////////////////////
( ! ) Fatal error: Uncaught Error: Call to undefined function FoundationPress\Blocks\acf_register_block_type() in /.../Local Sites/foundationpress-mediadudes/app/public/wp-content/themes/FoundationPress/inc/blocks/block-accordion.php on line 16
( ! ) Error: Call to undefined function FoundationPress\Blocks\acf_register_block_type() in /.../Local Sites/foundationpress-mediadudes/app/public/wp-content/themes/FoundationPress/inc/blocks/block-accordion.php on line 16
Call Stack
#	Time	Memory	Function	Location
1	0.0112	409048	{main}( )	.../customize.php:0
2	0.0112	410320	require_once( '/.../Local Sites/foundationpress-mediadudes/app/public/wp-admin/admin.php' )	.../customize.php:13
3	0.0112	410960	require_once( '/.../Local Sites/foundationpress-mediadudes/app/public/wp-load.php' )	.../admin.php:34
4	0.0113	411400	require_once( '/.../Local Sites/foundationpress-mediadudes/app/public/wp-config.php' )	.../wp-load.php:37
5	0.0113	421688	require_once( '/.../Local Sites/foundationpress-mediadudes/app/public/wp-settings.php' )	.../wp-config.php:77
6	0.1467	3411336	do_action( )	.../wp-settings.php:560
7	0.1467	3411712	WP_Hook->do_action( )	.../plugin.php:484
8	0.1467	3411712	WP_Hook->apply_filters( )	.../class-wp-hook.php:316
9	0.1654	3690224	ACF->init( )	.../class-wp-hook.php:292
10	0.1743	4353656	do_action( )	.../acf.php:325
11	0.1743	4354032	WP_Hook->do_action( )	.../plugin.php:484
12	0.1743	4354032	WP_Hook->apply_filters( )	.../class-wp-hook.php:316
13	0.1743	4355160	FoundationPress\Blocks\Block_Accordion::register_block_type( )	.../class-wp-hook.php:292

There has been a critical error on this website. Please check your site admin email inbox for instructions.
/////////////////////////////////////////////////////

Steps to recreate:
cd my-wordpress-folder/wp-content/themes/
git clone https://github.com/MEDIADUDES/FoundationPress.git
cd FoundationPress
npm install
composer install
npm run build
live preview the newly built theme

Thank you.
