### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function FoundationPress\Blocks\acf_register_block_type

### ISSUE THREAD

**Issue by CL1001** [MEDIADUDES/FoundationPress#9]
I ried appending to a closed issue, which apparently won't be re-opened.

**How can this bug be reproduced?**

cd my-wordpress-folder/wp-content/themes/
git clone https://github.com/MEDIADUDES/FoundationPress.git
cd FoundationPress
npm install
composer install
npm run build
live preview the newly built theme

**What did you expect to happen?**
 Expected to see live preview

**What happened instead?**
 Fatal Error

**Please List the Following:**

    OS & version: Fedora Core 28 64
    Node version (node -v) [Node v4+ is required] : v10.19.0 & v11.13.0
    FoundationPress version (see line 3 in package.json): "version": "3.4.1", (actually this is in line 4)
    Foundation version (found in node_modules/foundation-sites/package.json) : foundation-sites@6.6.3

**Include Test Case** (if applicable):  
Not possible

/////////////////////////////////////////////////////
( ! ) Fatal error: Uncaught Error: Call to undefined function FoundationPress\Blocks\acf_register_block_type() in /.../Local Sites/foundationpress-mediadudes/app/public/wp-content/themes/FoundationPress/inc/blocks/block-accordion.php on line 16
( ! ) Error: Call to undefined function FoundationPress\Blocks\acf_register_block_type() in /.../Local Sites/foundationpress-mediadudes/app/public/wp-content/themes/FoundationPress/inc/blocks/block-accordion.php on line 16
Call Stack
Time Memory Function Location

1 0.0112 409048 {main}( ) .../customize.php:0
2 0.0112 410320 require_once( '/.../Local Sites/foundationpress-mediadudes/app/public/wp-admin/admin.php' ) .../customize.php:13
3 0.0112 410960 require_once( '/.../Local Sites/foundationpress-mediadudes/app/public/wp-load.php' ) .../admin.php:34
4 0.0113 411400 require_once( '/.../Local Sites/foundationpress-mediadudes/app/public/wp-config.php' ) .../wp-load.php:37
5 0.0113 421688 require_once( '/.../Local Sites/foundationpress-mediadudes/app/public/wp-settings.php' ) .../wp-config.php:77
6 0.1467 3411336 do_action( ) .../wp-settings.php:560
7 0.1467 3411712 WP_Hook->do_action( ) .../plugin.php:484
8 0.1467 3411712 WP_Hook->apply_filters( ) .../class-wp-hook.php:316
9 0.1654 3690224 ACF->init( ) .../class-wp-hook.php:292
10 0.1743 4353656 do_action( ) .../acf.php:325
11 0.1743 4354032 WP_Hook->do_action( ) .../plugin.php:484
12 0.1743 4354032 WP_Hook->apply_filters( ) .../class-wp-hook.php:316
13 0.1743 4355160 FoundationPress\Blocks\Block_Accordion::register_block_type( ) .../class-wp-hook.php:292

There has been a critical error on this website. Please check your site admin email inbox for instructions.
/////////////////////////////////////////////////////
Thank you.

**Comment by CL1001** [comment]
Why closed?

**Comment by SimonMayerhofer** [comment]
Pushed a fix :) you can see it referenced in the closed message:

<img width="555" alt="Screenshot 2021-06-28 at 13 05 08" src="https://user-images.githubusercontent.com/4314302/123626766-7c83fb00-d811-11eb-975d-0b5dece6885e.png">
